### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by badgerman11** [debsahu/ESP8266-NeoAirPainter#1]
Hi,
I can't build it. Do you know why? Error:

`collect2.exe: error: ld returned 1 exit status
*** [.pio\build\nodemcuv2\firmware.elf] Error 1
 [FAILED] Took 8.36 seconds`

**Comment by badgerman11** [comment]
Got it, in Arudino IDE everything works fine.

**Comment by debsahu** [comment]
Sorry couldn't reply earlier. Glad you figured out yourself, I'll test why it fails on PIO.
